backend:
  name: git-gateway
  repo: codeforharima/codeforharima.github.io
  branch: main

media_folder: "content/images"
public_folder: "/images"
sort: "date:desc"

collections:
  - name: "blog"
    label: "ブログ"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
      - {
          label: "カテゴリー",
          name: "category",
          widget: "string",
          default: "blog",
        }
